version: "3.8"

services:
  eventhub.api:
    image: eventhub.api
    container_name: eventhub.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - eventhub.db
      - eventhub.cache
      - eventhub.seq
      - eventhub.hangfire
      - eventhub.minio
    ports:
      - "8002:80"
    build:
      context: ../source/EventHub.Presentation
      dockerfile: Dockerfile
    restart: on-failure

# network section
networks:
  default:
    name: eventhub
    driver: bridge
