version: '3.8'

services:
  eventhub.api:
    image: eventhub-api
    container_name: eventhub.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    build:
      context: ..
      dockerfile: source/EventHub.Presentation/Dockerfile
    restart: always
    ports:
      - "5002:80"

networks:
  default:
    name: eventhub
    driver: bridge