namespace EventHub.Domain.Shared.Enums.Function;

public enum EFunctionCode
{
    GENERAL,
    GENERAL_CATEGORY,
    GENERAL_EVENT,
    GENERAL_REVIEW,
    GENERAL_EXPENSE,
    GENERAL_TICKET,
    GENERAL_PAYMENT,
    GENERAL_CHAT,
    GENERAL_COUPON,

    ADMINISTRATION,
    ADMINISTRATION_USER,
    ADMINISTRATION_ROLE,
    ADMINISTRATION_FUNCTION,
    ADMINISTRATION_COMMAND,
    ADMINISTRATION_PERMISSION
}
