version: '3.8'

services:
  eventhub.api:
    image: eventhubcontainer.azurecr.io/eventhub-api:linux-latest
    container_name: eventhub.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnectionString=Server=eventhub.db,1433;Database=EventHubDB;User Id=sa;Password=@Admin123;TrustServerCertificate=True;Multipleactiveresultsets=true"
      - "ConnectionStrings:CacheConnectionString=eventhub.cache:6379"
      - "SeqConfiguration:ServerUrl=http://eventhub.seq:5341"
      - "HangfireSettings:Storage:ConnectionString=mongodb://admin:admin@eventhub.hangfire:27017/hangfire-webapi?authSource=admin"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always